Feature/disabled email inputs
vtex-apps/login pull request #217
Opened 2020-08-19 23:48 UTC by rafarubim

#### What problem is this solving?
This adds `disabledEmailInputs` prop to disable editing in email fields. This will be used by checkout to lock a known user

#### How to test it?

Go into
https://rafaprtest5--storecomponents.myvtex.com/
and click `Sign in`, then `Receive access code by email` or `Sign in with email and password`. You'll see the email input disabled.
If you add the query string `?userEmail=example@email.com`, you can lock a specific email.

#### Screenshots or example usage:

![image](https://user-images.githubusercontent.com/22064061/90700883-51c62f00-e25d-11ea-9160-75e5ac003480.png)

2020-08-20 17:43 UTC, psmeireles submitted a review, later dismissed

2020-08-24 22:30 UTC, rafarubim commented on docs/README.md
> +| `disabledEmailInputs`                 | `Boolean` | Disables all email inputs                                                                     | -             |
I just included it!

2020-08-25 13:40 UTC, guerreirobeatriz commented on docs/README.md
> +| `disabledEmailInputs`                 | `Boolean` | Disables all email inputs                                                                     | false         |
```suggestion
| `disabledEmailInputs`     | `boolean` | Whether Checkout should allow user email editing (`true`) or not (`false`).   | `false`       |
```

2020-08-25 13:40 UTC, guerreirobeatriz commented on docs/README.md
> +| `disabledEmailInputs`                 | `Boolean` | Disables all email inputs                                                                     | false         |
```suggestion
| `disabledEmailInputs`                 | `boolean` | Whether Checkout should allow user email editing (`true`) or not (`false`).      | `false`         |
```

2020-08-25 20:02 UTC, rafarubim commented on docs/README.md
> +| `disabledEmailInputs`                 | `Boolean` | Disables all email inputs                                                                     | false         |
Ops, forgot about that, sorry!

2020-08-27 19:28 UTC, guerreirobeatriz submitted a review, later dismissed

2020-09-14 14:25 UTC, rnbez requested changes

2020-09-14 14:25 UTC, rnbez commented on react/components/EmailAndPassword.js
> +    /** Disables editing email input */
```suggestion
    /** Disables email input */
```

2020-09-14 14:25 UTC, rnbez commented on react/components/EmailVerification.js
> +    /** Disables editing email input */
```suggestion
    /** Disables email input */
```

2020-09-14 14:25 UTC, rnbez commented on react/propTypes.js
> +  /** Disables editing in all email inputs */
```suggestion
  /** Disables email inputs */
```

2020-09-14 14:25 UTC, rnbez commented on docs/README.md
> +| `disabledEmailInputs`     | `boolean` | Whether Checkout should allow user email editing (`true`) or not (`false`).   | `false`       |
Wait, what if I'm building a b2b store and I have a customized way of setting up the user's email and I don't want it to change? The Checkout is the use case for now, but certainly not the only one.

2020-09-14 14:25 UTC, rnbez commented on docs/README.md
> +| `disabledEmailInputs`                 | `boolean` | Whether Checkout should allow user email editing (`true`) or not (`false`).      | `false`         |
Same.

2020-10-14 14:04 UTC, rnbez submitted a review, later dismissed

2020-11-10 18:04 UTC, merged